<?php

namespace ApplicationBundle\Repository;
use Doctrine\ORM\NoResultException;

/**
 * fractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FractionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUserID($id)
	{
		$qb = $this->_em->createQueryBuilder('f');

		$qb -> select('f')
				->from('ApplicationBundle:Fraction', 'f')
				->where('f.utilisateur = :id')
				->setParameter('id', $id);

		$requete = $qb->getQuery();

		try
		{
			$result = $requete->getResult();
		}
		catch (\Doctrine\ORM\NoResultException $e)
		{
			$result = "NoResultException";
		}

		return $result;
	}

}
