<?php

namespace ApplicationBundle\Repository;

/**
 * fractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FractionRepository extends \Doctrine\ORM\EntityRepository
{
}
