<?php

namespace ApplicationBundle\Repository;
use Doctrine\ORM\NoResultException;

/**
 * MouvementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByFraction($id)
  {
    $qb = $this->_em->createQueryBuilder('m');

    $qb -> select('m')
        ->from('ApplicationBundle:Mouvement', 'm')
        ->where('m.fraction = :id')
        ->orderBy('m.date', 'ASC')
        ->setParameter('id', $id)
        ;

    $requete = $qb->getQuery();

    try
		{
			$result = $requete->getResult();
		}
		catch (\Doctrine\ORM\NoResultException $e)
		{
			$result = "NoResultException";
		}

		return $result;
  }

  public function findBudgetRestant($id)
  {
    $nom = "Budget Restant";

    $qb = $this->_em->createQueryBuilder('m');

    $qb -> select('m')
        ->from('ApplicationBundle:Mouvement', 'm')
        ->where('m.fraction = :id')
        ->andWhere('m.nom = :nom')
        ->setParameter('id', $id)
        ->setParameter('nom', $nom);

    $requete = $qb->getQuery();

    try
		{
			$result = $requete->getSingleResult();
		}
		catch (\Doctrine\ORM\NoResultException $e)
		{
			$result = "NoResultException";
		}

		return $result;
  }

  public function findByMouvementId($id)
  {
    $qb = $this->_em->createQueryBuilder('m');

    $qb ->select('m')
        ->from('ApplicationBundle:Mouvement', 'm')
        ->where('m.id = :id')
        ->setParameter('id', $id);

    $requete = $qb->getQuery();

    try
    {
      $result = $requete->getSingleResult();
    }
    catch (\Doctrine\ORM\NoResultException $e)
    {
      $result = "NoResultException";
    }

    return $result;
  }

}
