<?php

namespace ApplicationBundle\Repository;

/**
 * sousFractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousFractionRepository extends \Doctrine\ORM\EntityRepository
{
}
