<?php

namespace ApplicationBundle\Repository;
use Doctrine\ORM\NoResultException;


/**
 * utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByEmail($email, $motDePasse)
	{
		$qb = $this->_em->createQueryBuilder('u');

		$qb ->select('u')
			->from('ApplicationBundle:Utilisateur', 'u')
			->where('u.email = :email')
			->andWhere('u.motDePasse = :motDePasse')
			->setParameter('email', $email)
			->setParameter('motDePasse', $motDePasse);

		$requete = $qb->getQuery();

		try
		{
			$result = $requete->getSingleResult();
		}
		catch (\Doctrine\ORM\NoResultException $e)
		{
			$result = "NoResultException";
		}

		return $result;
	}

	public function insertUser($nom, $prenom, $email, $dateNaiss, $daltonisme, $motDePasse)
	{
		$qb = $this->_em->createQueryBuilder('u');
		$qb ->insert('Utilisateur')
			->values(['nom', 'prenom', 'email', 'dateNaiss', 'daltonisme', 'daltonisme'])
			->setParameter(0, $nom)
			->setParameter(1, $prenom)
			->setParameter(2, $email)
			->setParameter(3, $dateNaiss)
			->setParameter(4, $daltonisme);

	}
}
