application_homepage:
    path:     /
    defaults: { _controller: ApplicationBundle:Default:index }

#application_connexion:
#    path:     /connexion
#    defaults: { _controller: ApplicationBundle:User:connexion }

connexion:
    path:     /connexion
    defaults: { _controller: ApplicationBundle:User:connexion }

inscription:
    path:     /inscription
    defaults: { _controller: ApplicationBundle:User:inscription }
