application_homepage:
    path:     /
    defaults: { _controller: ApplicationBundle:Default:index }

application_connexion:
    path:     /connexion
    defaults: { _controller: ApplicationBundle:Default:connexion }
