application_homepage:
    path:     /accueil
    defaults: { _controller: ApplicationBundle:Default:index }

#application_connexion:
#    path:     /connexion
#    defaults: { _controller: ApplicationBundle:User:connexion }

connexion:
    path:     /connexion
    defaults: { _controller: ApplicationBundle:User:connexion }

inscription:
    path:     /inscription
    defaults: { _controller: ApplicationBundle:User:inscription }

reinitailisation:
    path:     /reinitialisation
    defaults: { _controller:  ApplicationBundle:User:reinitialisationMotDePasse }

partition:
    path:     /partition
    defaults: { _controller: ApplicationBundle:Default:partition }

simulation:
    path:     /simulation
    defaults: { _controller: ApplicationBundle:Default:simulation }

entrerMouvement:
    path:     /entrerMouvement
    defaults: { _controller: ApplicationBundle:Default:entrerMouvement }

modifierMouvement:
    path:     /modifierMouvement
    defaults: { _controller: ApplicationBundle:Default:modifierMouvement }

aide:
    path:     /aide
    defaults: { _controller: ApplicationBundle:Default:aide }

parametres:
    path:     /parametres
    defaults: { _controller: ApplicationBundle:User:parametresUtilisateur }

deconnexion:
    path:     /deconnexion
    defaults: { _controller: ApplicationBundle:User:deconnexion }
